# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xunuo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib
from matplotlib.figure import Figure
from pyqtgraph import GraphicsLayoutWidget

matplotlib.use('Qt5Agg')
# 使用 matplotlib中的FigureCanvas (在使用 Qt5 Backends中 FigureCanvas继承自QtWidgets.QWidget)
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import sys, math
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import Qt
import matplotlib.pyplot as plt
import numpy as np




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 470)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -140, 931, 691))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/ASUS/Desktop/qiaoliang.png"))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 741, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_canshu = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Button_canshu.setObjectName("Button_canshu")
        self.horizontalLayout.addWidget(self.Button_canshu)
        self.button_lishi = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_lishi.setObjectName("button_lishi")
        self.horizontalLayout.addWidget(self.button_lishi)
        self.button_kaishi = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_kaishi.setObjectName("button_kaishi")
        self.horizontalLayout.addWidget(self.button_kaishi)
        self.button_zanting = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_zanting.setObjectName("button_zanting")
        self.horizontalLayout.addWidget(self.button_zanting)

        # self.textEdit_huatu = QtWidgets.QTextEdit(self.centralwidget)
        # self.textEdit_huatu.setGeometry(QtCore.QRect(20, 110, 751, 181))
        # self.textEdit_huatu.setObjectName("textEdit_huatu")
        self.graph_huatu = GraphicsLayoutWidget(self.centralwidget)
        self.graph_huatu.setGeometry(QtCore.QRect(20, 110, 751, 181))
        self.graph_huatu.setObjectName("graph_huatu")


        self.button_chaxun = QtWidgets.QPushButton(self.centralwidget)
        self.button_chaxun.setGeometry(QtCore.QRect(510, 350, 75, 23))
        self.button_chaxun.setObjectName("button_chaxun")
        self.label_weizhi = QtWidgets.QLabel(self.centralwidget)
        self.label_weizhi.setGeometry(QtCore.QRect(50, 350, 72, 15))
        self.label_weizhi.setObjectName("label_weizhi")
        self.label_weizhi.setStyleSheet('color: white')
        self.lineEdit_weihzi = QtWidgets.QLineEdit(self.centralwidget)#注意打错了
        self.weizhi = []
        self.lineEdit_weihzi.setGeometry(QtCore.QRect(110, 350, 113, 21))
        self.lineEdit_weihzi.setObjectName("lineEdit_weihzi")
        self.label_yingbian = QtWidgets.QLabel(self.centralwidget)
        self.label_yingbian.setGeometry(QtCore.QRect(280, 350, 72, 15))
        self.label_yingbian.setObjectName("label_yingbian")
        self.label_yingbian.setStyleSheet('color:white')
        self.lineEdit_yingbian = QtWidgets.QLineEdit(self.centralwidget)
        self.yingbian = []
        self.lineEdit_yingbian.setGeometry(QtCore.QRect(330, 350, 113, 21))
        self.lineEdit_yingbian.setObjectName("lineEdit_yingbian")
        self.label_picjingbao = QtWidgets.QLabel(self.centralwidget)
        self.label_picjingbao.setGeometry(QtCore.QRect(620, 310, 151, 101))
        self.label_picjingbao.setText("")
        self.label_picjingbao.setPixmap(QtGui.QPixmap("C:/Users/ASUS/Desktop/redlight.jpg"))
        self.label_picjingbao.setScaledContents(True)
        self.label_picjingbao.setObjectName("label_picjingbao")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_canshu.setText(_translate("MainWindow", "参数设置"))
        self.button_lishi.setText(_translate("MainWindow", "历史查询"))
        self.button_kaishi.setText(_translate("MainWindow", "开始测量"))
        self.button_zanting.setText(_translate("MainWindow", "暂停"))
        self.button_chaxun.setText(_translate("MainWindow", "查询"))
        self.label_weizhi.setText(_translate("MainWindow", "位置："))
        self.label_yingbian.setText(_translate("MainWindow", "应变："))
